spring:
  application:
    name: eboutique

  datasource:
    username: eboutique
    password: eboutique
    url: jdbc:mysql://localhost:3306/e_boutique

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
